export const BASE_WORKER_CREEP_BODY = [WORK, CARRY, MOVE];
export const WORKER_CREEP_BODY_LVL2 = [WORK, WORK, CARRY, CARRY, MOVE, MOVE];
export const WORKER_CREEP_BODY_LVL3 = [WORK, WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE];
export const WORKER_CREEP_BODY_LVL4 = [WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE];
export const WORKER_CREEP_BODY_LVL5 = [WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE];

export const BASE_CARRIER_CREEP_BODY = [CARRY, CARRY, MOVE];
export const CARRIER_CREEP_BODY_LVL2 = [CARRY, CARRY, CARRY, CARRY, MOVE, MOVE];
export const CARRIER_CREEP_BODY_LVL3 = [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE];

export const HARVESTERS_COUNT_LIMIT = 4;
export const HARVESTER_BODY = WORKER_CREEP_BODY_LVL3;

export const MINERS_COUNT_LIMIT = 2;
export const MINER_BODY = WORKER_CREEP_BODY_LVL4;

export const GUARDS_COUNT_LIMIT = 0;
export const GUARD_BODY = [TOUGH, TOUGH, TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK, ATTACK];

export const RANGE_GUARDS_COUNT_LIMIT = 3;
export const RANGE_GUARD_BODY = [TOUGH, TOUGH, TOUGH, MOVE, MOVE, MOVE, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, MOVE, MOVE, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK, RANGED_ATTACK];

export const BUILDERS_COUNT_LIMIT = 2;
export const BUILDER_BODY = WORKER_CREEP_BODY_LVL2;

export const UPGRADERS_COUNT_LIMIT = 2;
export const UPGRADER_BODY = WORKER_CREEP_BODY_LVL2;

export const REPAIRERS_COUNT_LIMIT = 3;
export const REPAIRER_BODY = WORKER_CREEP_BODY_LVL3;
export const REPAIRER_HEALTH_LIMIT_RATIO = 0.5;

export const WALL_KEEPERS_COUNT_LIMIT = 2;
export const RAMPART_INITIAL_HITS = 5000;
export const WALL_DESIRED_HITS_LOW = 50000;
export const WALL_DESIRED_HITS_HIGH = 70000;
export const WALL_KEEPER_BODY = WORKER_CREEP_BODY_LVL3;

export const SPAWN_KEEPERS_COUNT_LIMIT = 3;
export const SPAWN_KEEPER_BODY = BASE_CARRIER_CREEP_BODY;

export const TOWER_KEEPERS_COUNT_LIMIT = 1;
export const TOWER_KEEPER_BODY = CARRIER_CREEP_BODY_LVL3;

export const GRAVE_KEEPERS_COUNT_LIMIT = 1;
export const GRAVE_KEEPER_BODY = CARRIER_CREEP_BODY_LVL2;
export const GRAVE_KEEPERS_LOOT_BORDERS = true;

export const ENERGY_AGGREGATORS_COUNT_LIMIT = 1;
export const ENERGY_AGGREGATOR_BODY = CARRIER_CREEP_BODY_LVL3;

export const LINK_KEEPERS_COUNT_LIMIT = 1;
export const LINK_KEEPER_BODY = CARRIER_CREEP_BODY_LVL2;

export const ENERGY_CENTER = 'ENERGY_CENTER';
export const UPGRADE_LINK = 'UPGRADE_LINK';
export const ENERGY_PROVIDER = 'ENERGY_PROVIDER';
export const ENERGY_SOURCE_1 = 'ENERGY_SOURCE_1';

export const SUICIDE_CREEPS = true;
export const SUICIDE_TTL = 50;

export const RESOURCE_ASSIGN_NORMALIZE_DISTANCE = false;
export const RESOURCE_ASSIGN_ALGO_VERSION = 15;

export const TOWER_RANGE = 50;
export const TOWER_ATTACK_BORDERS = true;
export const GUARDS_ATTACK_BORDERS = true;
export const TERMINAL_ENERGY_REQUIREMENT = 5000;

