export const USE_PERMANENT_SAFE_MODE = false;

export const HARVESTERS_COUNT = 8;
export const HARVESTER_BODY = [WORK, CARRY, MOVE];
export const HARVESTER_ADVANCED_BODY = [WORK, WORK, CARRY, MOVE, MOVE];
export const HARVESTER_SUPER_ADVANCED_BODY = [WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE];

export const BUILDERS_COUNT = 2;
export const BUILDERS_ENERGY_LIMIT = 200;
export const BUILDER_BODY = [WORK, WORK, CARRY, CARRY, MOVE, MOVE];

export const UPGRADERS_COUNT = 2;
export const UPGRADERS_ENERGY_LIMIT = 200;
export const UPGRADER_BODY = [WORK, WORK, CARRY, CARRY, MOVE, MOVE];

export const REPAIRERS_COUNT = 7;
export const REPAIRERS_ENERGY_LIMIT = 100;
export const REPAIRER_BODY = [WORK, WORK, CARRY, CARRY, MOVE];
export const REPAIRER_ADVANCED_BODY = [WORK, WORK, WORK, CARRY, CARRY, MOVE, MOVE];

export const SPAWN_KEEPERS_COUNT = 1;
export const SPAWN_KEEPER_BODY = [CARRY, CARRY, MOVE, MOVE];

export const TTL_UNTIL_RENEW = 100;
export const TTL_RENEW_LIMIT = 600;
export const RENEW_CREEPS = false;

export const RESOURCE_ASSIGN_NORMALIZE_DISTANCE = false;
export const RESOURCE_ASSIGN_ALGO_VERSION = 11;
