export const BASE_WORKER_CREEP_BODY = [WORK, CARRY, MOVE];
export const WORKER_CREEP_BODY_LVL2 = [WORK, WORK, CARRY, CARRY, MOVE, MOVE];
export const WORKER_CREEP_BODY_LVL3 = [WORK, WORK, WORK, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE];
export const WORKER_CREEP_BODY_LVL4 = [WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE];
export const WORKER_CREEP_BODY_LVL5 = [WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE];
export const WORKER_CREEP_BODY_LVL6 = [WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE];
export const WORKER_CREEP_BODY_LVL7 = [WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE];

export const WORKER_BODIES = [
    WORKER_CREEP_BODY_LVL7,
    WORKER_CREEP_BODY_LVL6,
    WORKER_CREEP_BODY_LVL5,
    WORKER_CREEP_BODY_LVL4,
    WORKER_CREEP_BODY_LVL3,
    WORKER_CREEP_BODY_LVL2,
    BASE_WORKER_CREEP_BODY,
];

export const BASE_CARRIER_CREEP_BODY = [CARRY, CARRY, MOVE];
export const CARRIER_CREEP_BODY_LVL2 = [CARRY, CARRY, CARRY, CARRY, MOVE, MOVE];
export const CARRIER_CREEP_BODY_LVL3 = [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE];
export const CARRIER_CREEP_BODY_LVL4 = [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE];

export const CARRIER_BODIES = [
    CARRIER_CREEP_BODY_LVL4,
    CARRIER_CREEP_BODY_LVL3,
    CARRIER_CREEP_BODY_LVL2,
    BASE_CARRIER_CREEP_BODY,
];
